name: AccuKnox Scan Workflow

on:
  push:
    branches:
      - main
    # Exclude PR merges using 'push' types
    types:
      - pushed # Only trigger for direct commits

jobs:
  accuknox-cicd:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v4

      - name: Run Accuknox Secret Scan
        uses: pishone-accuknox/secret-scan-action@v1.2.5
        with:
          endpoint: ${{ vars.ENV }}
          tenant_id: ${{ vars.TENANT }}
          label: ${{ vars.LABEL }}
          token: ${{ secrets.TOKEN }}
          fail: "false"
